# This settings can be used to create repo level settings
repository: 
  # Name of the repo
  name: appooz-org-repo2
 
  # Create the repo if it is not existing
  force_create: true

  # This is the settings that need to be applied to all repositories in the org 
  # See https://developer.github.com/v3/repos/#edit for all available settings for a repository  
  # A short description of the repository that will show up on GitHub
  description: description of the repo
  
  # A URL with more information about the repository
  homepage: https://example.github.io/
    
  # Keep this as true for most cases
  # A lot of the policies below cannot be implemented on bare repos
  # Pass true to create an initial commit with empty README.
  auto_init: true
    
  # A comma-separated list of topics to set on the repository
  topics: 
  - github
  - safe-settings

  # Either `true` to make the repository private, or `false` to make it public. 
  # If this value is changed and if Org members cannot change the visibility of repos
  # it would result in an error when updating a repo
  private: false
  
  # Can be public or private. If your organization is associated with an enterprise account using 
  # GitHub Enterprise Cloud or GitHub Enterprise Server 2.20+, visibility can also be internal. 
  visibility: public
  
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: false
  
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false
  
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false
  
        
validator:
  pattern: '[a-zA-Z0-9_-]+_[a-zA-Z0-9_-]+.*' 
